### ISSUE TITLE
[Question] When mapping string that contains comma it's wrapped with additional quotes

### ISSUE THREAD

**Issue by rekosko** [leandromoh/RecordParser#102]
Hi there,

Thanks for the lib, works great and fast :) But lately I've been struggling with one issue I don't know if it's intended or not but for instance when I'm using `IVariableLengthWriter` when I map string property that contains a comma an example: `"XYZ XXX, S.L"` - it becomes `"\"XYZ XXX, S.L\""` so it adds two extra characters.

After writing to a file I have: `"XYZ XXX, S.L"` instead of just `XYZ XXX, S.L`

I ran some tests and I'm pretty sure the case is when string contains comma.

Why is that?

P.S.: forgot to mention that in file each written value is delimited by `;` and end values are wrapped with `"`

Here is example that I want to achieve:
`"000000";"COMPANY                                ";"XYZ XXX, S.L"`

**Comment by leandromoh** [comment]
hello @rekosko ! 

> Thanks for the lib, works great and fast :) 

Thank you for using it! and glad to know that it is helping to solve people real problems! it was the reason since the beginning

> I ran some tests and I'm pretty sure the case is when string contains comma.

yes, it is because of the comma char. In your cenario the two extra quotes around the value does not change the field content, just ensure to the consumers of the file that it is a single value. So it should not be a problem in pratice. Is it being a real problem in your cenario?

The reason: In many scenarios csv users/libraries do not compliant with [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt) standard. It defines that quoted char is `"` and field separator is `,` but in many cases we need to build something using different values, like in yours using `;` value.

So libraries usually should use a safe approach to guarantee that what is being write to a file can be read by another library/user, even in a different programming language. In RecordParser I choose to play safe and quote any text that contains one of the following values inside its inner content:

- user defined field separator
- , (comma character)
- \n (line break character)
- \r (carriage return character)
- " (double quote character)


if you really need to remove the extra quote around the field value, a possible workaround would be you removing the edge quotes in the "custom property converter". something like following

```cs
FuncSpanTIntBool func = (Span<char> dest, ReadOnlySpan<char> value) =>
{
    // not a quoted value
    if (value.Length < 3)
        return JustCopy(dest, value);

    // is it a quoted value? if no, just copy
    if (value[0] != '"')
        return JustCopy(dest, value);

    // ok, we got a quoted value. lets check its  inner content
    var innerContent = value.Slice(1, value.Length - 2);

    // does it contains any char that we judge ok to quote? if so, we are ok
    if (innerContent.ContainsAny(";\n\r\""))
        return JustCopy(dest, value);

    // ok, we got a quoted value that does not have any char that we judge ok to quote
    // lets go ahead just with its inner content
    return JustCopy(dest, innerContent);

    static (bool, int) JustCopy(Span<char> dest, ReadOnlySpan<char> value) =>
        value.TryCopyTo(dest)
            ? (true, value.Length)
            : (false, 0);
};

var writer = new VariableLengthWriterBuilder<(string Name, DateTime Birthday, string Surname)>()
    .Map(x => x.Name, 0, func)
    .Map(x => x.Birthday, 1, "yyyy.MM.dd")
    .Map(x => x.Surname, 2, func)
    .Build(";");

var instance = ("foo,bar,baz", new DateTime(2020, 05, 23), "Company xyz");

Span<char> destination = stackalloc char[100];

// Act

var success = writer.TryFormat(instance, destination, out var charsWritten);

// Assert

var result = destination.Slice(0, charsWritten);
```

after the parse:

![image](https://github.com/leandromoh/RecordParser/assets/11452028/60e1f255-380a-4fc7-ba2b-4bc9bafdc21f)

**Comment by rekosko** [comment]
@leandromoh thank you very much for giving me the solution to my problem :) I did something similar with my custom converter but just used `value.Trim('"')` instead.

So in the end you proved me that this is the way to go in my case. Once again thanks :)
