### ISSUE TITLE
[Question] Read LARGE CSV File in Chunk

### ISSUE THREAD

**Issue by ShaonDey** [leandromoh/RecordParser#96]
I have a LARGE CSV File with 100K Rows in it and one Header on top of it. Sample CSV:
```
Id,Reference,Amount
1,123456789,30
18,123-456-789,60.25
...
...
...
```

</br>

Is there a way to read this data in chunks? A batch of `N (500)` rows each time perhaps?

**Comment by leandromoh** [comment]
Hi @ShaonDey 

The library supports parsing files since version 2, (I will update readme soon). Since the library returns an `IEnumerable<T>` when reading files, you can use [Chunk method](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.chunk?view=net-8.0) of LINQ (.NET >= 6), or `Batch` method of [MoreLinq](https://github.com/morelinq/MoreLINQ), a well known third party library which has a lot of useful methods in spirit of LINQ.

Example: 

```c#
using var streamReader = new StreamReader(...);

// you can use VariableLengthWriterSequentialBuilder if you want to omit indexes

var parser = new VariableLengthReaderBuilder<YOUR_TYPE>()
    .Map(x => x.Id, 0)
    .Map(x => x.Reference, 1)
    .Map(x => x.Amount, 2)
    .Build(",", CultureInfo.InvariantCulture);

var readOptions = new VariableLengthReaderOptions
{
    HasHeader = true,
    ParallelismOptions = new() { Enabled = [true|false] },
    ContainsQuotedFields = [true|false],
};

var items = streamReader.ReadRecords(parser, readOptions);

foreach (var batch in items.Chunk(500))
{
    ...
}
```

**Comment by ShaonDey** [comment]
@leandromoh, Will try this .Chunk() option. Similarly, I can also use .Skip().Take() methods by LINQ right?

<br/>

Can you please suggest a few configurations to fine-tune this process to be more performant? Especially the `ParallelismOptions`.
```
var builder = new VariableLengthReaderBuilder<(long ProductId, string AccountReference, decimal Amount)>()
    .Map(x => x.ProductId, 0)
    .Map(x => x.AccountReference, 1)
    .Map(x => x.Amount, 2);
var reader = builder.Build(",", CultureInfo.InvariantCulture);
var readerOptions = new VariableLengthReaderOptions
{
    HasHeader = true,
    ContainsQuotedFields = false,
    ParallelismOptions = new()
    {
        Enabled = true,
        EnsureOriginalOrdering = true,
        CancellationToken = cancellationToken
    }
};
using var streamReader = new StreamReader(csvFormFile.OpenReadStream());
var records = streamReader.ReadRecords(reader, readerOptions);
```

**Comment by leandromoh** [comment]
>  I can also use .Skip().Take() methods by LINQ right?

It is not usually a good idea in `IEnumerable`s, because it would be very inefficient if the sequence is lazy and if so you would need to iterate in the collection more than once (once per batch), however if your `IEnumerable` is a materialized collection, is ok because `Skip` and `Take` are optimized for collections (take a look at the code [here](https://github.com/dotnet/runtime/blob/779d53611efd10526ca2bc3e94ce13ee18ad493a/src/libraries/System.Linq/src/System/Linq/Partition.SpeedOpt.cs) for `EnumerablePartition`). So you could call `ToList` or `ToArray` once and use it for slice.. something like 
```c#
var materializedRecords = streamReader.ReadRecords(reader, readerOptions).ToList();
```

However, for performance reasons is better to avoid keep all records at the same time in the memory, specially for large files as your, so the best option still is `Chunk` or `Batch` methods.

- MoreLinq's Batch method in [stackoverflow answer](https://stackoverflow.com/a/13731823).
- [Explanation link](https://www.davidboike.dev/2010/08/batch-or-partition-a-collection-with-linq/) of why Skip + Take might be bad

Other relavant point is that records read from file are streamed by the library, and the content of the internal buffer changes as it goes forward through the file. So unless you save records somewhere or materialize they into a collection (like `ToList`, `ToArray`, etc) once you read the next record, you can not read the past record again (similar to `ReadLine()` from `TextReader` or `MoveNext()` from `IEnumerator`). So another advantage of Chunck/Batch is that you will not have this problem.

> Can you please suggest a few configurations to fine-tune this process to be more performant? Especially the ParallelismOptions.

Your configuration looks good to me, I would only complement setting the `MaxDegreeOfParallelism` property. Usually 4 is a good value, but it depends of how many cores you have avaible.

> var builder = new VariableLengthReaderBuilder<(long ProductId, string AccountReference, decimal Amount)>()

One question, is your type really a tuple? most examples on readme use tuples for simplicity, but the parser actually works for any type (classes, structs, records, arrays, tuples, etc) except anonymous types.

**Comment by ShaonDey** [comment]
First of all, thank you for your valuable input @leandromoh!

I'll go with one of these `Chunk` / `Batch` / `MoreLINQ`.

`MaxDegreeOfParallelism` is the setting I am not so sure about yet from my end actually. I'll take a deeper look into my system and then configure it accordingly.

The reason behind using a tuple is that after parsing the data I'll need to validate and then map it to a different class.

**Comment by leandromoh** [comment]
> First of all, thank you for your valuable input @leandromoh!

you are welcome! I am glad to help 😁

> MaxDegreeOfParallelism is the setting I am not so sure about yet from my end actually. I'll take a deeper look into my system and then configure it accordingly.

depending of performance demand, it is good to benchmark. I usually use [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet)

> The reason behind using a tuple is that after parsing the data I'll need to validate and then map it to a different class.

okay! no problem.

**Comment by leandromoh** [comment]
Do you have something else @ShaonDey ? If not, I will close the issue.

**Comment by ShaonDey** [comment]
That'd be all for now! Closing the issue.

**Comment by ShaonDey** [comment]
```
Id,Reference,Amount
1,123456789,30
18,123-456-789,60.25
```

@leandromoh, How can the CSV file's Header be validated? Whether CSV has that exact header as mentioned.

**Comment by leandromoh** [comment]
@ShaonDey Currently RecordParser just discards the header row, but you could check by your own doing something like following:

```c#
using System;
using System.Globalization;
using RecordParser.Builders.Reader;
using RecordParser.Extensions;
using System.IO;

var fileContent = 
    """
    Id,Reference,Amount
    1,123456789,30
    18,123-456-789,60.25
    """;

// I am using StringReader because in the example the content is a string
// but could be StreamReader or any TextReader
using TextReader textReader = new StringReader(fileContent);

var headerRow = textReader.ReadLine();
var headerFields = headerRow.Split(",");

Console.WriteLine(headerRow);

// your validation can be done here
if (headerFields[0] != "Id" || headerFields[1] != "Reference" || headerFields[2] != "Amount")
    throw new Exception ("some header is different of expected");

var builder = new VariableLengthReaderBuilder<Record>()
    .Map(x => x.Id, 0)
    .Map(x => x.Reference, 1)
    .Map(x => x.Amount, 2);

var reader = builder.Build(",", CultureInfo.InvariantCulture);
var readerOptions = new VariableLengthReaderOptions
{
    // false because we already consumed header manually
    HasHeader = false,
    ContainsQuotedFields = false,
    ParallelismOptions = new()
    {
        Enabled = true,
        EnsureOriginalOrdering = true,
    }
};

var records = textReader.ReadRecords(reader, readerOptions);

foreach(var r in records)
{
    Console.WriteLine(r);
}

public record class Record(int Id, string Reference, decimal Amount);
``` 

[dotnetfiddle](https://dotnetfiddle.net/VyHNCy)
